version: "2.2"

services:
    ade:
        container_name: ade-aa-ms
        build:
            context: ./
            dockerfile: Dockerfile
        environment: 
            - NODE_TLS_REJECT_UNAUTHORIZED=0
        env_file:
            - .env
        expose:
            - "3000"
        ports:
            - "3000:3000"
            - "5859:5859"
        image: node:12.18.0-alpine
        command: ["yarn", "start"]
        volumes:
            - ".:/usr/src/app:cached"