version: "2.2"

services:
    storage:
        image: azurite
        build:
            context: ./
            dockerfile: docker/azurite/Dockerfile
        ports:
            - "10000:10000"
            - "10001:10001"
            - "10002:10002"
        networks:
            - ade-net
            
    ade:
        container_name: ade-aa-ms
        build:
            context: ./
            dockerfile: Dockerfile
        environment: 
            - NODE_TLS_REJECT_UNAUTHORIZED=0
        env_file:
            - .env
        expose:
            - "3000"
        ports:
            - "3000:3000"
            - "5859:5859"
        image: node:12.18.0-alpine
        command: ["yarn", "start"]
        volumes:
            - ".:/usr/src/app:cached"
        depends_on: 
            - storage
        networks:
            - ade-net
    
networks:
    ade-net:
        driver: bridge
        driver_opts:
            com.docker.network.driver.mtu: 1450